.TH "ideviceinstaller" 1
.SH NAME
ideviceinstaller \- Manage apps on iOS devices.
.SH SYNOPSIS
.B ideviceinstaller
[OPTIONS]

.SH DESCRIPTION

Allows to enumerate, install, upgrade, and uninstall apps on iOS devices.

.SH COMMANDS
.TP
.B list
List installed apps on the device.
.RS
.TP
\-b <bundleID>
Only query for given bundle identifier (can be passed multiple times)
.TP
\-o list_user
list user apps only (apps installed by the user)
.B This is the default.
.TP
\-o list_system
list system apps only (apps available from the system firmware)
.TP
\-o list_all
list all types of apps
.TP
\-o xml
print output in xml format (PList)
.RE
.TP
.B install PATH
Install app from a package file specified by PATH. PATH can also be a .ipcc
file for carrier bundle installation or a .app directory for developer
app installation.

.TP
.B uninstall BUNDLEID
Uninstall app specified by BUNDLEID.

.TP
.B upgrade PATH
Upgrade app from a package file specified by PATH.

.TP
.B restore BUNDLEID
Restore archived app specified by BUNDLEID.

.TP
.B list-archives
List archived apps on the device.
.RS
.TP
\-o xml
print full output as xml plist
.RE

.TP
.B archive BUNDLEID
Archive app specified by BUNDLEID.
.RS
.TP
\-o uninstall
uninstall the package after making an archive
.TP
\-o app_only
archive application data only
.TP
\-o docs_only
archive documents (user data) only
.TP
\-o copy=PATH
copy the app archive to directory PATH when done
.TP
\-o remove
only valid when copy=PATH is used: remove after copy
.RE

.TP
.B remove-archive BUNDLEID
Remove app archive specified by BUNDLEID.


.SH OPTIONS
.TP
.B \-u, \-\-udid UDID
Target specific device by UDID.
.TP
.B \-n, \-\-network
Connect to network device.
.TP
.B \-w, \-\-notify-wait
Wait for app installed/uninstalled notification to before reporting success of operation.
.TP
.B \-h, \-\-help
Print usage information.
.TP
.B \-d, \-\-debug
Enable communication debugging.
.TP
.B \-v, \-\-version
Print version information.

.SH AUTHORS
Nikias Bassen

Martin Szulecki

.SH ON THE WEB
https://libimobiledevice.org

https://github.com/libimobiledevice/ideviceinstaller
